void main (){
  print("Welcome to Dart Programming");
  //Arithematic Operators.
  int n1=50;
  int n2=30;
  int sum;
  int mul;
  int div;
  double cross;
  sum=n1+n2;
  mul=n1*n2;
  div=n1%n2;//it gives us reminder 
  cross=n1/n2;//gives us Division completly
  print('sum is: $sum');
  print('Multiplication of numbers is: $mul');
  print('Divisionof of numbers is: $div');
  print('/ of numbers is: $cross');
  

}